version: '3.8'

services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: johndoe
      POSTGRES_PASSWORD: randompassword
      POSTGRES_DB: mydb
    ports:
      - 5433:5432
    volumes:
      - ./docker/pgdata:/var/lib/postgresql/data
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3333:3333
    volumes:
      - .:/app
    depends_on:
      - db