#!/bin/bash

echo "🔧 SonarQube - Configuração Inicial"
echo "================================="
echo ""

echo "📋 Passos para configurar SonarQube:"
echo ""

echo "🌐 OPÇÃO 1: SonarCloud (Recomendado - Gratuito)"
echo "----------------------------------------------"
echo "1. Acesse: https://sonarcloud.io"
echo "2. Faça login com sua conta GitHub"
echo "3. Importe este repositório"
echo "4. Copie o token gerado"
echo "5. Configure os secrets no GitHub:"
echo "   - SONAR_TOKEN: <seu-token>"
echo "6. Execute: git push (para triggerar o workflow)"
echo ""

echo "🐳 OPÇÃO 2: SonarQube Local"
echo "---------------------------"
echo "1. Execute: ./scripts/run-sonar-analysis.sh"
echo "2. Aguarde inicialização (pode demorar)"
echo "3. Acesse: http://localhost:9000"
echo "4. Login: admin / admin"
echo "5. Configure seu projeto"
echo ""

echo "📦 OPÇÃO 3: Instalação Global do SonarScanner"
echo "--------------------------------------------"
echo "# Ubuntu/Debian:"
echo "curl -sSLo sonar-scanner.zip https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-4.8.0.2856-linux.zip"
echo "unzip sonar-scanner.zip"
echo "sudo mv sonar-scanner-4.8.0.2856-linux /opt/sonar-scanner"
echo "sudo ln -s /opt/sonar-scanner/bin/sonar-scanner /usr/local/bin/"
echo ""

echo "# macOS:"
echo "brew install sonar-scanner"
echo ""

echo "🔧 Scripts Disponíveis:"
echo "----------------------"
echo "npm run lint          # Verificar código com ESLint"
echo "npm run lint:fix      # Corrigir problemas automaticamente"
echo "npm run sonar:up      # Subir SonarQube local"
echo "npm run sonar:down    # Parar SonarQube local"
echo "npm run sonar         # Análise (com sonar-scanner instalado)"
echo "npm run sonar:local   # Análise com Docker"
echo "npm run quality:check # Lint + Análise SonarQube"
echo ""

echo "📊 Métricas que serão analisadas:"
echo "--------------------------------"
echo "✅ Bugs e vulnerabilidades"
echo "✅ Code smells"
echo "✅ Complexidade ciclomática"
echo "✅ Duplicação de código"
echo "✅ Maintainability rating"
echo "✅ Security rating"
echo "✅ Reliability rating"
echo ""

echo "🎯 Quality Gates configurados:"
echo "-----------------------------"
echo "• Coverage: > 80% (quando houver testes)"
echo "• Duplicated Lines: < 3%"
echo "• Maintainability Rating: A"
echo "• Reliability Rating: A"
echo "• Security Rating: A"
echo ""

echo "🚀 Para começar agora:"
echo "---------------------"
echo "1. npm install                    # Instalar dependências"
echo "2. npm run lint                   # Verificar qualidade local"
echo "3. ./scripts/run-sonar-analysis.sh # Análise completa"
echo ""
